
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cem
 */
public class adminPaneli extends javax.swing.JFrame {
    
    DefaultTableModel model;
    UyeIslemleri uyeIslemleri=new UyeIslemleri();
    DefaultTableModel model1;
    MemurIslemleri memurIslemleri=new MemurIslemleri();
    
    
    
    /**
     * Creates new form yoneticiEkrani
     */
    public adminPaneli() {
        
        initComponents();
        model1=(DefaultTableModel)tbl_memur.getModel();
        model=(DefaultTableModel)tbl_uyeler.getModel();
        UyeGoruntule();
        memurGoruntule();
        
        
        
    }
    
   
    
    public void memurGoruntule(){
        model1.setRowCount(0);
        ArrayList<Memur> gorevliler=new ArrayList<Memur>();
        
        gorevliler=memurIslemleri.memurlariGetir();
        if(gorevliler!=null){
            for(Memur gorevli:gorevliler){
                
                Object[] eklenecek={gorevli.getMemurID(),gorevli.getMemurAd(),gorevli.getMemurSoyad(),gorevli.getMemurEmail(),gorevli.getMemurParola()};
                model1.addRow(eklenecek);
                
                
                
                
                
            }
            
        }
        
        
        
    }
    public void UyeGoruntule(){
        
        model.setRowCount(0);
        
        ArrayList<Uyeler> uyeler=new ArrayList<Uyeler>();
        
        uyeler=uyeIslemleri.uyeleriGetir();
        if(uyeler!=null)
        {
            for(Uyeler uye:uyeler){
                Object[] eklenecek={uye.getUyeAdi(),uye.getUyeSoyad(),uye.getParola(),uye.getTel(),uye.getEmail(),uye.getCinsiyet()
                ,uye.getSehir(),uye.getIlce(),uye.getMahalle(),uye.getSokak(),uye.getBinaNo(),uye.getDaireNo(),uye.getPostaKodu(),uye.getUyeNo()};
                model.addRow(eklenecek);
                
            }
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_memurAdi = new javax.swing.JTextField();
        tf_memurSoyad = new javax.swing.JTextField();
        tf_memurParola = new javax.swing.JTextField();
        btn_gorevliSil = new javax.swing.JButton();
        btn_gorevliGuncelle = new javax.swing.JButton();
        btn_gorevliEkle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_memur = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        tf_memurEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_uyeAdi = new javax.swing.JTextField();
        tf_uyeSoyadi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_uyeParola = new javax.swing.JTextField();
        btn_ekle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rb_kadın = new javax.swing.JRadioButton();
        rb_erkek = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        tf_uyeTel = new javax.swing.JTextField();
        tf_uyeEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_ilce = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_mahalle = new javax.swing.JTextField();
        tf_sokak = new javax.swing.JTextField();
        tf_binaNo = new javax.swing.JTextField();
        tf_postaKodu = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_uyeler = new javax.swing.JTable();
        tf_daireNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_il = new javax.swing.JTextField();
        Istatislik = new javax.swing.JPanel();
        btn_cizgiGrafik = new javax.swing.JButton();
        btn_pastaGrafik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Ad:");

        jLabel2.setText("Soyad:");

        jLabel3.setText("Parola:");

        tf_memurAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_memurAdiActionPerformed(evt);
            }
        });

        tf_memurSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_memurSoyadActionPerformed(evt);
            }
        });

        tf_memurParola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_memurParolaActionPerformed(evt);
            }
        });

        btn_gorevliSil.setBackground(new java.awt.Color(255, 255, 255));
        btn_gorevliSil.setText("MEMUR SİL");
        btn_gorevliSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gorevliSilActionPerformed(evt);
            }
        });

        btn_gorevliGuncelle.setBackground(new java.awt.Color(255, 255, 255));
        btn_gorevliGuncelle.setText("MEMUR GÜNCELLE");
        btn_gorevliGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gorevliGuncelleActionPerformed(evt);
            }
        });

        btn_gorevliEkle.setBackground(new java.awt.Color(255, 255, 255));
        btn_gorevliEkle.setText("MEMUR EKLE");
        btn_gorevliEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gorevliEkleActionPerformed(evt);
            }
        });

        tbl_memur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Memur No", "Adı", "Soyadı", "Email", "Parola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_memur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_memurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_memur);

        jLabel18.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_memurParola, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_gorevliEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_memurSoyad)
                        .addComponent(tf_memurAdi)
                        .addComponent(tf_memurEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_gorevliGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(btn_gorevliSil, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_memurAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_memurSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_memurEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_memurParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gorevliEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gorevliGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gorevliSil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Memur İşlemleri", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel4.setText("Ad:");

        tf_uyeAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uyeAdiActionPerformed(evt);
            }
        });

        tf_uyeSoyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uyeSoyadiActionPerformed(evt);
            }
        });

        jLabel5.setText("Soyad:");

        jLabel6.setText("Parola:");

        tf_uyeParola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uyeParolaActionPerformed(evt);
            }
        });

        btn_ekle.setBackground(new java.awt.Color(255, 255, 255));
        btn_ekle.setText("ÜYE EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_sil.setBackground(new java.awt.Color(255, 255, 255));
        btn_sil.setText(" ÜYEYİ SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_guncelle.setBackground(new java.awt.Color(255, 255, 255));
        btn_guncelle.setText("ÜYEYİ GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        jLabel7.setText("Email:");

        jLabel8.setText("Telefon:");

        jLabel9.setText("Cinsiyet:");

        buttonGroup1.add(rb_kadın);
        rb_kadın.setText("Kadın");
        rb_kadın.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_kadınActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_erkek);
        rb_erkek.setText("Erkek");
        rb_erkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_erkekActionPerformed(evt);
            }
        });

        jLabel10.setText("Adres:");

        tf_uyeTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uyeTelActionPerformed(evt);
            }
        });

        tf_uyeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uyeEmailActionPerformed(evt);
            }
        });

        jLabel11.setText("İl");

        jLabel12.setText("İlçe");

        jLabel13.setText("Mahalle");

        jLabel14.setText("Sokak");

        jLabel15.setText("Bina No");

        jLabel16.setText("Posta Kodu");

        tbl_uyeler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adı", "Soyadı", "Parola", "Telefon No", "Email", "Cinsiyet", "Şehir", "İlçe", "Mahalle", "Sokak", "Bina No", "Daire No", "Posta Kodu", "No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_uyeler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_uyelerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_uyeler);

        jLabel17.setText("Daire No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(395, 395, 395)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(tf_daireNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_postaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addComponent(tf_uyeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_erkek)
                                .addGap(24, 24, 24)
                                .addComponent(rb_kadın))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_uyeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(tf_il, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(tf_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_mahalle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_sokak, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_binaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel15))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_uyeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_uyeParola)
                                                .addComponent(tf_uyeSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(254, 254, 254))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tf_uyeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_uyeSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_uyeParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_uyeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_uyeTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb_erkek)
                    .addComponent(rb_kadın))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_mahalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_sokak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_binaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_daireNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_postaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Üye İşlemleri", jPanel2);

        Istatislik.setBackground(new java.awt.Color(153, 153, 153));

        btn_cizgiGrafik.setBackground(new java.awt.Color(255, 255, 255));
        btn_cizgiGrafik.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cizgiGrafik.setText("İstatislik Çizgi Grafiklerini Görüntüle");
        btn_cizgiGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cizgiGrafikActionPerformed(evt);
            }
        });

        btn_pastaGrafik.setBackground(new java.awt.Color(255, 255, 255));
        btn_pastaGrafik.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_pastaGrafik.setText("İstatislik Pasta Grafiklerini Görüntüle");
        btn_pastaGrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pastaGrafikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IstatislikLayout = new javax.swing.GroupLayout(Istatislik);
        Istatislik.setLayout(IstatislikLayout);
        IstatislikLayout.setHorizontalGroup(
            IstatislikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IstatislikLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(IstatislikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_pastaGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cizgiGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        IstatislikLayout.setVerticalGroup(
            IstatislikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IstatislikLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_cizgiGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btn_pastaGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin İşlemleri", Istatislik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_memurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_memurMouseClicked
        int selectedRow=tbl_memur.getSelectedRow();
        tf_memurAdi.setText(model1.getValueAt(selectedRow, 1).toString());
        tf_memurSoyad.setText(model1.getValueAt(selectedRow,2).toString());
        tf_memurEmail.setText(model1.getValueAt(selectedRow, 3).toString());
        tf_memurParola.setText(model1.getValueAt(selectedRow, 4).toString());

    }//GEN-LAST:event_tbl_memurMouseClicked

    private void btn_gorevliEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gorevliEkleActionPerformed
        String gorevliAdi=tf_memurAdi.getText();
        String gorevliSoyad=tf_memurSoyad.getText();
        String gorevliEmail=tf_memurEmail.getText();
        String gorevliParola=tf_memurParola.getText();

        memurIslemleri.memurEkle(gorevliAdi, gorevliSoyad, gorevliEmail, gorevliParola);
        memurGoruntule();

    }//GEN-LAST:event_btn_gorevliEkleActionPerformed

    private void btn_gorevliGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gorevliGuncelleActionPerformed
        int selectedRow=tbl_memur.getSelectedRow();

        if(selectedRow==-1){

            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this, "Memurlar tablosu şu anda boş...");
            }
            else {
                JOptionPane.showMessageDialog(null, "Lütfen güncellenecek memuru seçiniz...");
            }
        }
        else {
            String memurAd=tf_memurAdi.getText();
            String memurSoyad=tf_memurSoyad.getText();
            String memurEmail=tf_memurEmail.getText();
            String memurParola=tf_memurParola.getText();
            int memurID=(int)model1.getValueAt(selectedRow, 0);
            memurIslemleri.memurGuncelle(memurAd, memurSoyad, memurEmail, memurParola, memurID);
           memurGoruntule();
            JOptionPane.showMessageDialog(null, "Görevli başarıyla güncellendi...");

        }

    }//GEN-LAST:event_btn_gorevliGuncelleActionPerformed

    private void btn_gorevliSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gorevliSilActionPerformed
        int selectedRow=tbl_memur.getSelectedRow();

        if(selectedRow==-1){

            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "Görevli tablosu şu anda boş...");
            }
            else {
                JOptionPane.showMessageDialog(null, "Lütfen silinecek görevliyi seçiniz...");
            }
        }
        else {
            int gorevliNo=(int)model1.getValueAt(selectedRow, 0);

            memurIslemleri.memurSil(gorevliNo);
            memurGoruntule();
            JOptionPane.showMessageDialog(null, "Gorevli başarıyla silindi...");

        }

    }//GEN-LAST:event_btn_gorevliSilActionPerformed

    private void tf_memurParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_memurParolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_memurParolaActionPerformed

    private void tf_memurSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_memurSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_memurSoyadActionPerformed

    private void tf_memurAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_memurAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_memurAdiActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void tbl_uyelerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_uyelerMouseClicked

        int selectedRow=tbl_uyeler.getSelectedRow();

        tf_uyeAdi.setText(model.getValueAt(selectedRow, 0).toString());
        tf_uyeSoyadi.setText(model.getValueAt(selectedRow, 1).toString());
        tf_uyeParola.setText(model.getValueAt(selectedRow, 2).toString());
        tf_uyeTel.setText(model.getValueAt(selectedRow, 3).toString());
        tf_uyeEmail.setText(model.getValueAt(selectedRow, 4).toString());

        if(model.getValueAt(selectedRow, 5).toString().equalsIgnoreCase("erkek")) rb_erkek.setSelected(true);
        else rb_kadın.setSelected(true);

        tf_il.setText(model.getValueAt(selectedRow, 6).toString());
        tf_ilce.setText(model.getValueAt(selectedRow, 7).toString());
        tf_mahalle.setText(model.getValueAt(selectedRow, 8).toString());
        tf_sokak.setText(model.getValueAt(selectedRow, 9).toString());
        tf_binaNo.setText(model.getValueAt(selectedRow, 10).toString());
        tf_daireNo.setText(model.getValueAt(selectedRow, 11).toString());
        tf_postaKodu.setText(model.getValueAt(selectedRow, 12).toString());

    }//GEN-LAST:event_tbl_uyelerMouseClicked

    private void tf_uyeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uyeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_uyeEmailActionPerformed

    private void tf_uyeTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uyeTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_uyeTelActionPerformed

    private void rb_erkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_erkekActionPerformed

    }//GEN-LAST:event_rb_erkekActionPerformed

    private void rb_kadınActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_kadınActionPerformed

    }//GEN-LAST:event_rb_kadınActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed

        int selectedRow=tbl_uyeler.getSelectedRow();

        if(selectedRow==-1){

            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this, "Üyeler tablosu şu anda boş...");
            }
            else {
                JOptionPane.showMessageDialog(null, "Lütfen güncellenecek üyeyi seçiniz...");
            }
        }
        else {
            String ad=tf_uyeAdi.getText();
            String soyad=tf_uyeSoyadi.getText();
            String parola=tf_uyeParola.getText();
            String email=tf_uyeEmail.getText();
            String telefon=tf_uyeTel.getText();
            String cinsiyet;
            if(rb_erkek.isSelected()) cinsiyet="erkek";
            else cinsiyet="kadın";
            String il=tf_il.getText();
            String ilce=tf_ilce.getText();
            String mahalle=tf_mahalle.getText();
            String sokak=tf_sokak.getText();
            String binaNo=tf_binaNo.getText();
            String daireNo=tf_daireNo.getText();
            String postaKodu=tf_postaKodu.getText();
            int uyeNo=(int)model.getValueAt(selectedRow, 13);
            uyeIslemleri.uyeGuncelle(ad, soyad, parola, telefon,email, cinsiyet, uyeNo);
            uyeIslemleri.adresGuncelle(il, ilce, mahalle, sokak, binaNo, daireNo, postaKodu, uyeNo);
            UyeGoruntule();

        }

    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed

        int selectedRow=tbl_uyeler.getSelectedRow();
        if(selectedRow==-1){

            if(model.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null, "Üyeler tablosu şu anda boş...");
            }
            else {
                JOptionPane.showMessageDialog(null, "Lütfen silinecek üyeyi seçiniz...");
            }
        }
        else {
            int uyeNo=(int)model.getValueAt(selectedRow, 13);

            uyeIslemleri.uyeSil(uyeNo);
            UyeGoruntule();
            

        }
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed

        String ad=tf_uyeAdi.getText();
        String soyad=tf_uyeSoyadi.getText();
        String parola=tf_uyeParola.getText();
        String email=tf_uyeEmail.getText();
        String telefon=tf_uyeTel.getText();
        String cinsiyet;
        if(rb_erkek.isSelected()) cinsiyet="erkek";
        else cinsiyet="kadın";
        String il=tf_il.getText();
        String ilce=tf_ilce.getText();
        String mahalle=tf_mahalle.getText();
        String sokak=tf_sokak.getText();
        String binaNo=tf_binaNo.getText();
        String daireNo=tf_daireNo.getText();
        String postaKodu=tf_postaKodu.getText();

        uyeIslemleri.adresEkle(il, ilce, mahalle, sokak, binaNo, daireNo, postaKodu);
        uyeIslemleri.uyeEkle(ad, soyad, parola,telefon,email, cinsiyet);

        UyeGoruntule();

    }//GEN-LAST:event_btn_ekleActionPerformed

    private void tf_uyeParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uyeParolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_uyeParolaActionPerformed

    private void tf_uyeSoyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uyeSoyadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_uyeSoyadiActionPerformed

    private void tf_uyeAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uyeAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_uyeAdiActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btn_cizgiGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cizgiGrafikActionPerformed
       
       
        
        CizgiGrafigiCizimIslemleri grafik=new CizgiGrafigiCizimIslemleri();
            
        CizgiGrafikEkrani ekran=new CizgiGrafikEkrani("Grafik");
        ekran.setVisible(true);
        ekran.setResizable(true);
        ekran.setSize(1000,900);
       
        
        ekran.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
        ekran.add(grafik);
        
        
    }//GEN-LAST:event_btn_cizgiGrafikActionPerformed

    private void btn_pastaGrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pastaGrafikActionPerformed
        
        PastaGrafigiCizimIslemleri grafik=new PastaGrafigiCizimIslemleri();
            
        PastaGrafikEkrani ekran=new PastaGrafikEkrani("Grafik");
        ekran.setVisible(true);
        ekran.setResizable(true);
        ekran.setSize(1000,900);
       
        
        ekran.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
        ekran.add(grafik);
        
        
        
        
        
    }//GEN-LAST:event_btn_pastaGrafikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Istatislik;
    private javax.swing.JButton btn_cizgiGrafik;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_gorevliEkle;
    private javax.swing.JButton btn_gorevliGuncelle;
    private javax.swing.JButton btn_gorevliSil;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_pastaGrafik;
    private javax.swing.JButton btn_sil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rb_erkek;
    private javax.swing.JRadioButton rb_kadın;
    private javax.swing.JTable tbl_memur;
    private javax.swing.JTable tbl_uyeler;
    private javax.swing.JTextField tf_binaNo;
    private javax.swing.JTextField tf_daireNo;
    private javax.swing.JTextField tf_il;
    private javax.swing.JTextField tf_ilce;
    private javax.swing.JTextField tf_mahalle;
    private javax.swing.JTextField tf_memurAdi;
    private javax.swing.JTextField tf_memurEmail;
    private javax.swing.JTextField tf_memurParola;
    private javax.swing.JTextField tf_memurSoyad;
    private javax.swing.JTextField tf_postaKodu;
    private javax.swing.JTextField tf_sokak;
    private javax.swing.JTextField tf_uyeAdi;
    private javax.swing.JTextField tf_uyeEmail;
    private javax.swing.JTextField tf_uyeParola;
    private javax.swing.JTextField tf_uyeSoyadi;
    private javax.swing.JTextField tf_uyeTel;
    // End of variables declaration//GEN-END:variables
}
